import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/base.scss";
import Link from "next/link";
import Github from "@/components/github";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <div className="container">
          <div className="inner">
            <header>
              <Link className="title" href="/">
                wkd2ev
              </Link>
              <Link href="https://github.com/dkpark10/wkd2ev">
                <Github />
              </Link>
            </header>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
